language: generic
sudo: required

services:
  - docker
before_install:
  - docker build -t yehoshua305/react -f Dockerfile.dev . 

script:
  - docker run -e CI=true yehoshua305/react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "yehoshua305-react"
  env: "Yehoshua305react-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-327071640737"
  # bucket_path: "yehoshua305-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"